apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodeapp
  name: nodeapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodeapp
  strategy: {}
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - image: mohamedshibl/nodeapp
        name: nodeapp
        resources: {}
status: {}
