apiVersion: v1
kind: Service
metadata:
  name: nodeapp-lb
  annotations:
    kubernetes.io/role/elb: 1
spec:
  type: LoadBalancer
  selector:
    app: nodeapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
